name: Run CI CD
on:
  - push
  - workflow_dispatch

# here I decided to group them to make sure only on actions run at a time.
concurrency:
  group: ci-cd-group-${{ github.ref}}
  cancel-in-progress: false
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm i
          CI=true npm run test:unit

  build_dev_image:
    uses: 'playsoil/todo-ui/.github/workflows/build.yml@master'
    needs: unit_test
    secrets: inherit
    with:
      app_base_url: 'http://88.198.112.124:8081'
      tag: 'dev'

  deploy-to-dev:
    uses: 'playsoil/todo-ui/.github/workflows/deploy.yml@master'
    needs: build_dev_image
    secrets: inherit
    with:
      app_port: 81
      app_base_url: 'http://88.198.112.124:8081'
      tag: 'dev'

  e2e-tests:
    uses: 'playsoil/todo-ui/.github/workflows/e2e.yml@master'
    needs: deploy-to-dev

  build_production_image:
    uses: 'playsoil/todo-ui/.github/workflows/build.yml@master'
    needs: e2e-tests
    secrets: inherit
    with:
      app_base_url: 'http://88.198.112.124:8080'
      tag: 'latest'

  deploy-to-production:
    uses: 'playsoil/todo-ui/.github/workflows/deploy.yml@master'
    needs: build_production_image
    secrets: inherit
    with:
      app_port: 80
      app_base_url: 'http://88.198.112.124:8080'
      tag: 'latest'
