name: Run CI CD
'on': push
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm ci
          npm run build
          npm run test:unit
  build_image:
    runs-on: ubuntu-latest
    needs: unit_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the app
        run: |
          npm ci
          npm run build
      - name: Build Docker image
        run: |
          docker build -t todo-ui-app:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker tag todo-ui-app:latest hemn791/todo-ui-app:latest
          docker push hemn791/todo-ui-app:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            docker stop todo-ui-app-2
            docker rm todo-ui-app-2
            docker pull hemn791/todo-ui-app:latest
            docker run -d --name todo-ui-app-2 -p 80:80 hemn791/todo-ui-app:latest
