name: Run Unit Tests
'on': push
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm ci
          npm run build
          npm run test:unit
  build_image:
    runs-on: ubuntu-latest
    needs: unit_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the app
        run: |
          npm ci
          npm run build
      - name: Build Docker image
        run: |
          docker build -t todo-ui-app:latest .
