on:
  workflow_call:
  workflow_dispatch:
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'playsoil/todo-ui'
      - run: |
          npm i
          npx cypress run --e2e
